# Generated by Django 3.2.4 on 2021-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegroups',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telegroups',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
