# Generated by Django 3.2.4 on 2021-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210616_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegroups',
            old_name='desc',
            new_name='Groupdesc',
        ),
        migrations.RenameField(
            model_name='telegroups',
            old_name='name',
            new_name='Groupname',
        ),
    ]
