# Generated by Django 3.2.4 on 2021-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_telegroups_yourname'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegroups',
            name='Groupimg',
            field=models.ImageField(default=-1.0, upload_to=''),
            preserve_default=False,
        ),
    ]
