# Generated by Django 3.2.4 on 2021-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_telegroups_groupimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
