# Generated by Django 3.2.4 on 2021-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegroups',
            name='Groupimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
